### ISSUE TITLE
add test job against sdk dev branch

### ISSUE THREAD

**Issue by joshgav** [Azure-Samples/azure-sdk-for-go-samples#24]
We currently test against the master branch in the SDK repo: http://azuresdkci.cloudapp.net/view/golang/job/azure-sdk-for-go-samples/

Can we add a test against the dev branch so we can prep for upcoming releases?

**Comment by mcardosos** [comment]
Added a `dev` branch here too, and that is the one that tests against dev branches of `azure-sdk-for-go` and `go-autorest`. To make this happen the dep file was modified with this: 
``` toml
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  branch = "dev"
[[override]]
  name = "github.com/Azure/go-autorest"
  branch = "dev"
```
